### ISSUE TITLE
How to create new boards? Where is Admin panel?

### ISSUE THREAD

**Issue by tunayuyar** [JokkeeZ/BoardLite#1]
Hi,

I was just searching new imageboard script to try found yours just now, I installed it but couldnt figure out how to create new boards and reach admin panel.

Is this functions implemented ?

Thanks.

**Comment by JokkeeZ** [comment]
No, those are not implemented (at least yet). You can create new boards via database at the moment. I might create admin panel and some other moderation features, like board creating and thread deleting etc. when I have more time. Thanks. :)
